// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

nonisolated public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == ShopifyAPI.SchemaMetadata {}

nonisolated public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == ShopifyAPI.SchemaMetadata {}

nonisolated public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == ShopifyAPI.SchemaMetadata {}

nonisolated public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == ShopifyAPI.SchemaMetadata {}

nonisolated public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: any ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  private static let objectTypeMap: [String: ApolloAPI.Object] = [
    "AbandonedCheckout": ShopifyAPI.Objects.AbandonedCheckout,
    "AbandonedCheckoutLineItem": ShopifyAPI.Objects.AbandonedCheckoutLineItem,
    "Abandonment": ShopifyAPI.Objects.Abandonment,
    "AddAllProductsOperation": ShopifyAPI.Objects.AddAllProductsOperation,
    "AdditionalFee": ShopifyAPI.Objects.AdditionalFee,
    "App": ShopifyAPI.Objects.App,
    "AppCatalog": ShopifyAPI.Objects.AppCatalog,
    "AppCredit": ShopifyAPI.Objects.AppCredit,
    "AppInstallation": ShopifyAPI.Objects.AppInstallation,
    "AppPurchaseOneTime": ShopifyAPI.Objects.AppPurchaseOneTime,
    "AppRevenueAttributionRecord": ShopifyAPI.Objects.AppRevenueAttributionRecord,
    "AppSubscription": ShopifyAPI.Objects.AppSubscription,
    "AppUsageRecord": ShopifyAPI.Objects.AppUsageRecord,
    "Article": ShopifyAPI.Objects.Article,
    "BasicEvent": ShopifyAPI.Objects.BasicEvent,
    "Blog": ShopifyAPI.Objects.Blog,
    "BulkOperation": ShopifyAPI.Objects.BulkOperation,
    "BusinessEntity": ShopifyAPI.Objects.BusinessEntity,
    "CalculatedOrder": ShopifyAPI.Objects.CalculatedOrder,
    "CartTransform": ShopifyAPI.Objects.CartTransform,
    "CashTrackingAdjustment": ShopifyAPI.Objects.CashTrackingAdjustment,
    "CashTrackingSession": ShopifyAPI.Objects.CashTrackingSession,
    "CatalogCsvOperation": ShopifyAPI.Objects.CatalogCsvOperation,
    "Channel": ShopifyAPI.Objects.Channel,
    "ChannelDefinition": ShopifyAPI.Objects.ChannelDefinition,
    "ChannelInformation": ShopifyAPI.Objects.ChannelInformation,
    "CheckoutProfile": ShopifyAPI.Objects.CheckoutProfile,
    "Collection": ShopifyAPI.Objects.Collection,
    "Comment": ShopifyAPI.Objects.Comment,
    "CommentEvent": ShopifyAPI.Objects.CommentEvent,
    "Company": ShopifyAPI.Objects.Company,
    "CompanyAddress": ShopifyAPI.Objects.CompanyAddress,
    "CompanyContact": ShopifyAPI.Objects.CompanyContact,
    "CompanyContactRole": ShopifyAPI.Objects.CompanyContactRole,
    "CompanyContactRoleAssignment": ShopifyAPI.Objects.CompanyContactRoleAssignment,
    "CompanyLocation": ShopifyAPI.Objects.CompanyLocation,
    "CompanyLocationCatalog": ShopifyAPI.Objects.CompanyLocationCatalog,
    "CompanyLocationStaffMemberAssignment": ShopifyAPI.Objects.CompanyLocationStaffMemberAssignment,
    "ConsentPolicy": ShopifyAPI.Objects.ConsentPolicy,
    "CookieBanner": ShopifyAPI.Objects.CookieBanner,
    "CurrencyExchangeAdjustment": ShopifyAPI.Objects.CurrencyExchangeAdjustment,
    "Customer": ShopifyAPI.Objects.Customer,
    "CustomerAccountAppExtensionPage": ShopifyAPI.Objects.CustomerAccountAppExtensionPage,
    "CustomerAccountNativePage": ShopifyAPI.Objects.CustomerAccountNativePage,
    "CustomerPaymentMethod": ShopifyAPI.Objects.CustomerPaymentMethod,
    "CustomerSegmentMember": ShopifyAPI.Objects.CustomerSegmentMember,
    "CustomerSegmentMembersQuery": ShopifyAPI.Objects.CustomerSegmentMembersQuery,
    "CustomerVisit": ShopifyAPI.Objects.CustomerVisit,
    "DeliveryCarrierService": ShopifyAPI.Objects.DeliveryCarrierService,
    "DeliveryCondition": ShopifyAPI.Objects.DeliveryCondition,
    "DeliveryCountry": ShopifyAPI.Objects.DeliveryCountry,
    "DeliveryCustomization": ShopifyAPI.Objects.DeliveryCustomization,
    "DeliveryLocationGroup": ShopifyAPI.Objects.DeliveryLocationGroup,
    "DeliveryMethod": ShopifyAPI.Objects.DeliveryMethod,
    "DeliveryMethodDefinition": ShopifyAPI.Objects.DeliveryMethodDefinition,
    "DeliveryParticipant": ShopifyAPI.Objects.DeliveryParticipant,
    "DeliveryProfile": ShopifyAPI.Objects.DeliveryProfile,
    "DeliveryProfileItem": ShopifyAPI.Objects.DeliveryProfileItem,
    "DeliveryPromiseParticipant": ShopifyAPI.Objects.DeliveryPromiseParticipant,
    "DeliveryPromiseProvider": ShopifyAPI.Objects.DeliveryPromiseProvider,
    "DeliveryProvince": ShopifyAPI.Objects.DeliveryProvince,
    "DeliveryRateDefinition": ShopifyAPI.Objects.DeliveryRateDefinition,
    "DeliveryZone": ShopifyAPI.Objects.DeliveryZone,
    "DiscountAutomaticBxgy": ShopifyAPI.Objects.DiscountAutomaticBxgy,
    "DiscountAutomaticNode": ShopifyAPI.Objects.DiscountAutomaticNode,
    "DiscountCodeNode": ShopifyAPI.Objects.DiscountCodeNode,
    "DiscountNode": ShopifyAPI.Objects.DiscountNode,
    "DiscountRedeemCodeBulkCreation": ShopifyAPI.Objects.DiscountRedeemCodeBulkCreation,
    "Domain": ShopifyAPI.Objects.Domain,
    "DraftOrder": ShopifyAPI.Objects.DraftOrder,
    "DraftOrderLineItem": ShopifyAPI.Objects.DraftOrderLineItem,
    "DraftOrderTag": ShopifyAPI.Objects.DraftOrderTag,
    "Duty": ShopifyAPI.Objects.Duty,
    "ExchangeLineItem": ShopifyAPI.Objects.ExchangeLineItem,
    "ExchangeV2": ShopifyAPI.Objects.ExchangeV2,
    "ExternalVideo": ShopifyAPI.Objects.ExternalVideo,
    "Fulfillment": ShopifyAPI.Objects.Fulfillment,
    "FulfillmentConstraintRule": ShopifyAPI.Objects.FulfillmentConstraintRule,
    "FulfillmentEvent": ShopifyAPI.Objects.FulfillmentEvent,
    "FulfillmentHold": ShopifyAPI.Objects.FulfillmentHold,
    "FulfillmentLineItem": ShopifyAPI.Objects.FulfillmentLineItem,
    "FulfillmentOrder": ShopifyAPI.Objects.FulfillmentOrder,
    "FulfillmentOrderDestination": ShopifyAPI.Objects.FulfillmentOrderDestination,
    "FulfillmentOrderLineItem": ShopifyAPI.Objects.FulfillmentOrderLineItem,
    "FulfillmentOrderMerchantRequest": ShopifyAPI.Objects.FulfillmentOrderMerchantRequest,
    "GenericFile": ShopifyAPI.Objects.GenericFile,
    "GiftCard": ShopifyAPI.Objects.GiftCard,
    "GiftCardCreditTransaction": ShopifyAPI.Objects.GiftCardCreditTransaction,
    "GiftCardDebitTransaction": ShopifyAPI.Objects.GiftCardDebitTransaction,
    "Image": ShopifyAPI.Objects.Image,
    "InventoryAdjustmentGroup": ShopifyAPI.Objects.InventoryAdjustmentGroup,
    "InventoryItem": ShopifyAPI.Objects.InventoryItem,
    "InventoryItemMeasurement": ShopifyAPI.Objects.InventoryItemMeasurement,
    "InventoryLevel": ShopifyAPI.Objects.InventoryLevel,
    "InventoryQuantity": ShopifyAPI.Objects.InventoryQuantity,
    "InventoryShipment": ShopifyAPI.Objects.InventoryShipment,
    "InventoryShipmentLineItem": ShopifyAPI.Objects.InventoryShipmentLineItem,
    "InventoryTransfer": ShopifyAPI.Objects.InventoryTransfer,
    "InventoryTransferLineItem": ShopifyAPI.Objects.InventoryTransferLineItem,
    "LineItem": ShopifyAPI.Objects.LineItem,
    "LineItemGroup": ShopifyAPI.Objects.LineItemGroup,
    "Link": ShopifyAPI.Objects.Link,
    "Location": ShopifyAPI.Objects.Location,
    "MailingAddress": ShopifyAPI.Objects.MailingAddress,
    "Market": ShopifyAPI.Objects.Market,
    "MarketCatalog": ShopifyAPI.Objects.MarketCatalog,
    "MarketRegionCountry": ShopifyAPI.Objects.MarketRegionCountry,
    "MarketWebPresence": ShopifyAPI.Objects.MarketWebPresence,
    "MarketingActivity": ShopifyAPI.Objects.MarketingActivity,
    "MarketingEvent": ShopifyAPI.Objects.MarketingEvent,
    "MediaImage": ShopifyAPI.Objects.MediaImage,
    "Menu": ShopifyAPI.Objects.Menu,
    "Metafield": ShopifyAPI.Objects.Metafield,
    "MetafieldDefinition": ShopifyAPI.Objects.MetafieldDefinition,
    "Metaobject": ShopifyAPI.Objects.Metaobject,
    "MetaobjectDefinition": ShopifyAPI.Objects.MetaobjectDefinition,
    "Model3d": ShopifyAPI.Objects.Model3d,
    "OnlineStoreTheme": ShopifyAPI.Objects.OnlineStoreTheme,
    "Order": ShopifyAPI.Objects.Order,
    "OrderAdjustment": ShopifyAPI.Objects.OrderAdjustment,
    "OrderDisputeSummary": ShopifyAPI.Objects.OrderDisputeSummary,
    "OrderTransaction": ShopifyAPI.Objects.OrderTransaction,
    "Page": ShopifyAPI.Objects.Page,
    "PaymentCustomization": ShopifyAPI.Objects.PaymentCustomization,
    "PaymentMandate": ShopifyAPI.Objects.PaymentMandate,
    "PaymentSchedule": ShopifyAPI.Objects.PaymentSchedule,
    "PaymentTerms": ShopifyAPI.Objects.PaymentTerms,
    "PaymentTermsTemplate": ShopifyAPI.Objects.PaymentTermsTemplate,
    "PointOfSaleDevice": ShopifyAPI.Objects.PointOfSaleDevice,
    "PriceList": ShopifyAPI.Objects.PriceList,
    "PriceRule": ShopifyAPI.Objects.PriceRule,
    "PriceRuleDiscountCode": ShopifyAPI.Objects.PriceRuleDiscountCode,
    "Product": ShopifyAPI.Objects.Product,
    "ProductBundleOperation": ShopifyAPI.Objects.ProductBundleOperation,
    "ProductConnection": ShopifyAPI.Objects.ProductConnection,
    "ProductDeleteOperation": ShopifyAPI.Objects.ProductDeleteOperation,
    "ProductDuplicateOperation": ShopifyAPI.Objects.ProductDuplicateOperation,
    "ProductEdge": ShopifyAPI.Objects.ProductEdge,
    "ProductFeed": ShopifyAPI.Objects.ProductFeed,
    "ProductOption": ShopifyAPI.Objects.ProductOption,
    "ProductOptionValue": ShopifyAPI.Objects.ProductOptionValue,
    "ProductSetOperation": ShopifyAPI.Objects.ProductSetOperation,
    "ProductTaxonomyNode": ShopifyAPI.Objects.ProductTaxonomyNode,
    "ProductVariant": ShopifyAPI.Objects.ProductVariant,
    "ProductVariantComponent": ShopifyAPI.Objects.ProductVariantComponent,
    "Publication": ShopifyAPI.Objects.Publication,
    "PublicationResourceOperation": ShopifyAPI.Objects.PublicationResourceOperation,
    "QuantityPriceBreak": ShopifyAPI.Objects.QuantityPriceBreak,
    "QueryRoot": ShopifyAPI.Objects.QueryRoot,
    "Refund": ShopifyAPI.Objects.Refund,
    "RefundShippingLine": ShopifyAPI.Objects.RefundShippingLine,
    "Return": ShopifyAPI.Objects.Return,
    "ReturnLineItem": ShopifyAPI.Objects.ReturnLineItem,
    "ReturnableFulfillment": ShopifyAPI.Objects.ReturnableFulfillment,
    "ReverseDelivery": ShopifyAPI.Objects.ReverseDelivery,
    "ReverseDeliveryLineItem": ShopifyAPI.Objects.ReverseDeliveryLineItem,
    "ReverseFulfillmentOrder": ShopifyAPI.Objects.ReverseFulfillmentOrder,
    "ReverseFulfillmentOrderDisposition": ShopifyAPI.Objects.ReverseFulfillmentOrderDisposition,
    "ReverseFulfillmentOrderLineItem": ShopifyAPI.Objects.ReverseFulfillmentOrderLineItem,
    "SaleAdditionalFee": ShopifyAPI.Objects.SaleAdditionalFee,
    "SavedSearch": ShopifyAPI.Objects.SavedSearch,
    "ScriptTag": ShopifyAPI.Objects.ScriptTag,
    "Segment": ShopifyAPI.Objects.Segment,
    "SellingPlan": ShopifyAPI.Objects.SellingPlan,
    "SellingPlanGroup": ShopifyAPI.Objects.SellingPlanGroup,
    "ServerPixel": ShopifyAPI.Objects.ServerPixel,
    "Shop": ShopifyAPI.Objects.Shop,
    "ShopAddress": ShopifyAPI.Objects.ShopAddress,
    "ShopPolicy": ShopifyAPI.Objects.ShopPolicy,
    "ShopifyPaymentsAccount": ShopifyAPI.Objects.ShopifyPaymentsAccount,
    "ShopifyPaymentsBalanceTransaction": ShopifyAPI.Objects.ShopifyPaymentsBalanceTransaction,
    "ShopifyPaymentsBankAccount": ShopifyAPI.Objects.ShopifyPaymentsBankAccount,
    "ShopifyPaymentsDispute": ShopifyAPI.Objects.ShopifyPaymentsDispute,
    "ShopifyPaymentsDisputeEvidence": ShopifyAPI.Objects.ShopifyPaymentsDisputeEvidence,
    "ShopifyPaymentsDisputeFileUpload": ShopifyAPI.Objects.ShopifyPaymentsDisputeFileUpload,
    "ShopifyPaymentsDisputeFulfillment": ShopifyAPI.Objects.ShopifyPaymentsDisputeFulfillment,
    "ShopifyPaymentsPayout": ShopifyAPI.Objects.ShopifyPaymentsPayout,
    "StaffMember": ShopifyAPI.Objects.StaffMember,
    "StandardMetafieldDefinitionTemplate": ShopifyAPI.Objects.StandardMetafieldDefinitionTemplate,
    "StoreCreditAccount": ShopifyAPI.Objects.StoreCreditAccount,
    "StoreCreditAccountCreditTransaction": ShopifyAPI.Objects.StoreCreditAccountCreditTransaction,
    "StoreCreditAccountDebitRevertTransaction": ShopifyAPI.Objects.StoreCreditAccountDebitRevertTransaction,
    "StoreCreditAccountDebitTransaction": ShopifyAPI.Objects.StoreCreditAccountDebitTransaction,
    "StoreCreditAccountExpirationTransaction": ShopifyAPI.Objects.StoreCreditAccountExpirationTransaction,
    "StorefrontAccessToken": ShopifyAPI.Objects.StorefrontAccessToken,
    "SubscriptionBillingAttempt": ShopifyAPI.Objects.SubscriptionBillingAttempt,
    "SubscriptionBillingCycleEditedContract": ShopifyAPI.Objects.SubscriptionBillingCycleEditedContract,
    "SubscriptionContract": ShopifyAPI.Objects.SubscriptionContract,
    "SubscriptionDraft": ShopifyAPI.Objects.SubscriptionDraft,
    "TaxonomyAttribute": ShopifyAPI.Objects.TaxonomyAttribute,
    "TaxonomyCategory": ShopifyAPI.Objects.TaxonomyCategory,
    "TaxonomyChoiceListAttribute": ShopifyAPI.Objects.TaxonomyChoiceListAttribute,
    "TaxonomyMeasurementAttribute": ShopifyAPI.Objects.TaxonomyMeasurementAttribute,
    "TaxonomyValue": ShopifyAPI.Objects.TaxonomyValue,
    "TenderTransaction": ShopifyAPI.Objects.TenderTransaction,
    "TransactionFee": ShopifyAPI.Objects.TransactionFee,
    "UnverifiedReturnLineItem": ShopifyAPI.Objects.UnverifiedReturnLineItem,
    "UrlRedirect": ShopifyAPI.Objects.UrlRedirect,
    "UrlRedirectImport": ShopifyAPI.Objects.UrlRedirectImport,
    "Validation": ShopifyAPI.Objects.Validation,
    "Video": ShopifyAPI.Objects.Video,
    "WebPixel": ShopifyAPI.Objects.WebPixel,
    "WebhookSubscription": ShopifyAPI.Objects.WebhookSubscription
  ]

  @_spi(Execution) public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    objectTypeMap[typename]
  }
}

nonisolated public enum Objects {}
nonisolated public enum Interfaces {}
nonisolated public enum Unions {}
